In [8]:
import pandas as pd

In [26]:
df = pd.read_csv("OneDrive/Masaüstü/vedat/CODİNG/AI_PYTHON/PythonVeriAnalizProjelerim/imdb_top_1000.csv")

In [28]:
df.head(3)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"

In [30]:
# Poster linki sütununu kaldırma
df = df.drop('Poster_Link', axis=1) # Satır içerisinden bir şey atmak istendiği zaman axis=0 derdik

In [32]:
df.head()

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [34]:
df["Runtime"]

0      142 min
1      175 min
2      152 min
3      202 min
4       96 min
        ...
995    115 min
996    201 min
997    118 min
998     97 min
999     86 min
Name: Runtime, Length: 1000, dtype: object

In [36]:
# Min yazılarını kaldırmamız gerek
df["Runtime"].str.replace(" min","")

0      142
1      175
2      152
3      202
4       96
      ...
995    115
996    201
997    118
998     97
999     86
Name: Runtime, Length: 1000, dtype: object

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   object
 1   Released_Year  1000 non-null   object
 2   Certificate    899 non-null    object
 3   Runtime        1000 non-null   object
 4   Genre          1000 non-null   object
 5   IMDB_Rating    1000 non-null   float64
 6   Overview       1000 non-null   object
 7   Meta_score     843 non-null    float64
 8   Director       1000 non-null   object
 9   Star1          1000 non-null   object
 10  Star2          1000 non-null   object
 11  Star3          1000 non-null   object
 12  Star4          1000 non-null   object
 13  No_of_Votes    1000 non-null   int64
 14  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(12)
memory usage: 117.3+ KB

In [40]:
# Runtime verileri hala string, sayısal değere çevirmemiz gerek
df["Runtime"] = df["Runtime"].str.replace(" min","").astype("int64")

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   object
 1   Released_Year  1000 non-null   object
 2   Certificate    899 non-null    object
 3   Runtime        1000 non-null   int64
 4   Genre          1000 non-null   object
 5   IMDB_Rating    1000 non-null   float64
 6   Overview       1000 non-null   object
 7   Meta_score     843 non-null    float64
 8   Director       1000 non-null   object
 9   Star1          1000 non-null   object
 10  Star2          1000 non-null   object
 11  Star3          1000 non-null   object
 12  Star4          1000 non-null   object
 13  No_of_Votes    1000 non-null   int64
 14  Gross          831 non-null    object
dtypes: float64(2), int64(2), object(11)
memory usage: 117.3+ KB

In [44]:
# Gross değerlerimiz de hala string gözüküyor, boş olan yani Nan değerleri kaldırıp sayısal değere çevirelim
df = df.dropna(subset=["Gross"])

In [46]:
df["Gross"] = df["Gross"].str.replace(",","").astype("float64")

In [48]:
# Dakikalık kazancını hesaplayalım
df["Dolar/Min"] = df["Gross"]/df["Runtime"]

In [50]:
df.head(4)

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Dolar/Min
0,The Shawshank Redemption,1994,A,142,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469.0,1.995878e+05
1,The Godfather,1972,A,175,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411.0,7.712366e+05
2,The Dark Knight,2008,UA,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444.0,3.518806e+06
3,The Godfather: Part II,1974,A,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000.0,2.836634e+05

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 831 entries, 0 to 997
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   831 non-null    object
 1   Released_Year  831 non-null    object
 2   Certificate    785 non-null    object
 3   Runtime        831 non-null    int64
 4   Genre          831 non-null    object
 5   IMDB_Rating    831 non-null    float64
 6   Overview       831 non-null    object
 7   Meta_score     750 non-null    float64
 8   Director       831 non-null    object
 9   Star1          831 non-null    object
 10  Star2          831 non-null    object
 11  Star3          831 non-null    object
 12  Star4          831 non-null    object
 13  No_of_Votes    831 non-null    int64
 14  Gross          831 non-null    float64
 15  Dolar/Min      831 non-null    float64
dtypes: float64(4), int64(2), object(10)
memory usage: 110.4+ KB

In [54]:
# Filmleri dakikalık kazançlarına göre büyükten küçüğe sıralayalım
df.sort_values(by="Dolar/Min",ascending = False)

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Dolar/Min
477,Star Wars: Episode VII - The Force Awakens,2015,U,138,"Action, Adventure, Sci-Fi",7.9,"As a new threat to the galaxy rises, Rey, a de...",80.0,J.J. Abrams,Daisy Ridley,John Boyega,Oscar Isaac,Domhnall Gleeson,860823,936662225.0,6.787407e+06
891,Incredibles 2,2018,UA,118,"Animation, Action, Adventure",7.6,The Incredibles family takes on a new mission ...,80.0,Brad Bird,Craig T. Nelson,Holly Hunter,Sarah Vowell,Huck Milner,250057,608581744.0,5.157472e+06
43,The Lion King,1994,U,88,"Animation, Adventure, Drama",8.5,Lion prince Simba and his father are targeted ...,88.0,Roger Allers,Rob Minkoff,Matthew Broderick,Jeremy Irons,James Earl Jones,942045,422783777.0,4.804361e+06
59,Avengers: Endgame,2019,UA,181,"Action, Adventure, Drama",8.4,After the devastating events of Avengers: Infi...,78.0,Anthony Russo,Joe Russo,Robert Downey Jr.,Chris Evans,Mark Ruffalo,809955,858373000.0,4.742392e+06
623,Avatar,2009,UA,162,"Action, Adventure, Fantasy",7.8,A paraplegic Marine dispatched to the moon Pan...,83.0,James Cameron,Sam Worthington,Zoe Saldana,Sigourney Weaver,Michelle Rodriguez,1118998,760507625.0,4.694492e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,Udaan,2010,UA,134,Drama,8.2,"Expelled from his school, a 16-year old boy re...",NaN,Vikramaditya Motwane,Rajat Barmecha,Ronit Roy,Manjot Singh,Ram Kapoor,42341,7461.0,5.567910e+01
605,Ajeossi,2010,R,119,"Action, Crime, Drama",7.8,A quiet pawnshop keeper with a violent past ta...,NaN,Jeong-beom Lee,Won Bin,Sae-ron Kim,Tae-hoon Kim,Hee-won Kim,62848,6460.0,5.428571e+01
390,Knockin' on Heaven's Door,1997,NaN,87,"Action, Crime, Comedy",8.0,Two terminally ill patients escape from a hosp...,NaN,Thomas Jahn,Til Schweiger,Jan Josef Liefers,Thierry van Werveke,Moritz Bleibtreu,27721,3296.0,3.788506e+01
624,Mr. Nobody,2009,R,141,"Drama, Fantasy, Romance",7.8,A boy stands on a station platform as a train ...,63.0,Jaco Van Dormael,Jared Leto,Sarah Polley,Diane Kruger,Linh Dan Pham,216421,3600.0,2.553191e+01
630,Adams æbler,2005,R,94,"Comedy, Crime, Drama",7.8,A neo-nazi sentenced to community service at a...,51.0,Anders Thomas Jensen,Ulrich Thomsen,Mads Mikkelsen,Nicolas Bro,Paprika Steen,45717,1305.0,1.388298e+01

In [56]:
df["Released_Year"].unique()

array(['1994', '1972', '2008', '1974', '1957', '2003', '1993', '2010',
       '1999', '2001', '1966', '2002', '1990', '1980', '1975', '2019',
       '2014', '1998', '1997', '1995', '1991', '1977', '1954', '2011',
       '2006', '2000', '1988', '1985', '1968', '1960', '1942', '1936',
       '1931', '2018', '2016', '2017', '2012', '2009', '2007', '1984',
       '1981', '1979', '1964', '1940', '2004', '1992', '1987', '1986',
       '1983', '1976', '1973', '1971', '1965', '1962', '1959', '1958',
       '1952', '1948', '1944', '1941', '1927', '1921', '2015', '2013',
       '2005', '1989', '1963', '1955', '1950', '1925', '1924', '1996',
       '1982', '1978', '1967', '1951', '1949', '1939', '1937', '1934',
       '1928', '1926', '1970', '1969', '1961', '1946', '1930', '1956',
       '1947', '1945', '1938', '1935', '1933', 'PG', '1953'], dtype=object)

In [58]:
df = df[df["Released_Year"] != "PG"]

In [60]:
df["Released_Year"] = df["Released_Year"].astype("float32")

In [62]:
filtre1 = df["Released_Year"] > 2016
filtre2 = df["Genre"].str.contains("Action")

In [64]:
a2016 = df[filtre1 & filtre2]

In [66]:
a2016

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Dolar/Min
58,Spider-Man: Into the Spider-Verse,2018.0,U,117,"Animation, Action, Adventure",8.4,Teen Miles Morales becomes the Spider-Man of h...,87.0,Bob Persichetti,Peter Ramsey,Rodney Rothman,Shameik Moore,Jake Johnson,375110,190241310.0,1.625994e+06
59,Avengers: Endgame,2019.0,UA,181,"Action, Adventure, Drama",8.4,After the devastating events of Avengers: Infi...,78.0,Anthony Russo,Joe Russo,Robert Downey Jr.,Chris Evans,Mark Ruffalo,809955,858373000.0,4.742392e+06
60,Avengers: Infinity War,2018.0,UA,149,"Action, Adventure, Sci-Fi",8.4,The Avengers and their allies must be willing ...,68.0,Anthony Russo,Joe Russo,Robert Downey Jr.,Chris Hemsworth,Mark Ruffalo,834477,678815482.0,4.555809e+06
129,Uri: The Surgical Strike,2018.0,UA,138,"Action, Drama, War",8.2,Indian army special forces execute a covert op...,NaN,Aditya Dhar,Vicky Kaushal,Paresh Rawal,Mohit Raina,Yami Gautam,43444,4186168.0,3.033455e+04
134,Baahubali 2: The Conclusion,2017.0,UA,167,"Action, Drama",8.2,"When Shiva, the son of Bahubali, learns about ...",NaN,S.S. Rajamouli,Prabhas,Rana Daggubati,Anushka Shetty,Tamannaah Bhatia,75348,20186659.0,1.208782e+05
202,Logan,2017.0,A,137,"Action, Drama, Sci-Fi",8.1,"In a future where mutants are nearly extinct, ...",77.0,James Mangold,Hugh Jackman,Patrick Stewart,Dafne Keen,Boyd Holbrook,647884,226277068.0,1.651657e+06
217,Ford v Ferrari,2019.0,UA,152,"Action, Biography, Drama",8.1,American car designer Carroll Shelby and drive...,81.0,James Mangold,Matt Damon,Christian Bale,Jon Bernthal,Caitriona Balfe,291289,117624028.0,7.738423e+05
340,Blade Runner 2049,2017.0,UA,164,"Action, Drama, Mystery",8.0,Young Blade Runner K's discovery of a long-bur...,81.0,Denis Villeneuve,Harrison Ford,Ryan Gosling,Ana de Armas,Dave Bautista,461823,92054159.0,5.613058e+05
473,Thor: Ragnarok,2017.0,UA,130,"Action, Adventure, Comedy",7.9,"Imprisoned on the planet Sakaar, Thor must rac...",74.0,Taika Waititi,Chris Hemsworth,Tom Hiddleston,Cate Blanchett,Mark Ruffalo,587775,315058289.0,2.423525e+06
573,Dunkirk,2017.0,UA,106,"Action, Drama, History",7.8,"Allied soldiers from Belgium, the British Empi...",94.0,Christopher Nolan,Fionn Whitehead,Barry Keoghan,Mark Rylance,Tom Hardy,555092,188373161.0,1.777105e+06
722,Deadpool 2,2018.0,R,119,"Action, Adventure, Comedy",7.7,Foul-mouthed mutant mercenary Wade Wilson (a.k...,66.0,David Leitch,Ryan Reynolds,Josh Brolin,Morena Baccarin,Julian Dennison,478586,324591735.0,2.727662e+06
725,Mission: Impossible - Fallout,2018.0,UA,147,"Action, Adventure, Thriller",7.7,"Ethan Hunt and his IMF team, along with some f...",86.0,Christopher McQuarrie,Tom Cruise,Henry Cavill,Ving Rhames,Simon Pegg,291257,220159104.0,1.497681e+06
887,Guardians of the Galaxy Vol. 2,2017.0,UA,136,"Action, Adventure, Comedy",7.6,The Guardians struggle to keep together as a t...,67.0,James Gunn,Chris Pratt,Zoe Saldana,Dave Bautista,Vin Diesel,569974,389813101.0,2.866273e+06
888,Baby Driver,2017.0,UA,113,"Action, Crime, Drama",7.6,After being coerced into working for a crime b...,86.0,Edgar Wright,Ansel Elgort,Jon Bernthal,Jon Hamm,Eiza González,439406,107825862.0,9.542112e+05
889,Only the Brave,2017.0,UA,134,"Action, Biography, Drama",7.6,Based on the true story of the Granite Mountai...,72.0,Joseph Kosinski,Josh Brolin,Miles Teller,Jeff Bridges,Jennifer Connelly,58371,18340051.0,1.368661e+05
891,Incredibles 2,2018.0,UA,118,"Animation, Action, Adventure",7.6,The Incredibles family takes on a new mission ...,80.0,Brad Bird,Craig T. Nelson,Holly Hunter,Sarah Vowell,Huck Milner,250057,608581744.0,5.157472e+06

In [68]:
a2016.sort_values(by="IMDB_Rating",ascending = False)

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Dolar/Min
58,Spider-Man: Into the Spider-Verse,2018.0,U,117,"Animation, Action, Adventure",8.4,Teen Miles Morales becomes the Spider-Man of h...,87.0,Bob Persichetti,Peter Ramsey,Rodney Rothman,Shameik Moore,Jake Johnson,375110,190241310.0,1.625994e+06
59,Avengers: Endgame,2019.0,UA,181,"Action, Adventure, Drama",8.4,After the devastating events of Avengers: Infi...,78.0,Anthony Russo,Joe Russo,Robert Downey Jr.,Chris Evans,Mark Ruffalo,809955,858373000.0,4.742392e+06
60,Avengers: Infinity War,2018.0,UA,149,"Action, Adventure, Sci-Fi",8.4,The Avengers and their allies must be willing ...,68.0,Anthony Russo,Joe Russo,Robert Downey Jr.,Chris Hemsworth,Mark Ruffalo,834477,678815482.0,4.555809e+06
129,Uri: The Surgical Strike,2018.0,UA,138,"Action, Drama, War",8.2,Indian army special forces execute a covert op...,NaN,Aditya Dhar,Vicky Kaushal,Paresh Rawal,Mohit Raina,Yami Gautam,43444,4186168.0,3.033455e+04
134,Baahubali 2: The Conclusion,2017.0,UA,167,"Action, Drama",8.2,"When Shiva, the son of Bahubali, learns about ...",NaN,S.S. Rajamouli,Prabhas,Rana Daggubati,Anushka Shetty,Tamannaah Bhatia,75348,20186659.0,1.208782e+05
202,Logan,2017.0,A,137,"Action, Drama, Sci-Fi",8.1,"In a future where mutants are nearly extinct, ...",77.0,James Mangold,Hugh Jackman,Patrick Stewart,Dafne Keen,Boyd Holbrook,647884,226277068.0,1.651657e+06
217,Ford v Ferrari,2019.0,UA,152,"Action, Biography, Drama",8.1,American car designer Carroll Shelby and drive...,81.0,James Mangold,Matt Damon,Christian Bale,Jon Bernthal,Caitriona Balfe,291289,117624028.0,7.738423e+05
340,Blade Runner 2049,2017.0,UA,164,"Action, Drama, Mystery",8.0,Young Blade Runner K's discovery of a long-bur...,81.0,Denis Villeneuve,Harrison Ford,Ryan Gosling,Ana de Armas,Dave Bautista,461823,92054159.0,5.613058e+05
473,Thor: Ragnarok,2017.0,UA,130,"Action, Adventure, Comedy",7.9,"Imprisoned on the planet Sakaar, Thor must rac...",74.0,Taika Waititi,Chris Hemsworth,Tom Hiddleston,Cate Blanchett,Mark Ruffalo,587775,315058289.0,2.423525e+06
573,Dunkirk,2017.0,UA,106,"Action, Drama, History",7.8,"Allied soldiers from Belgium, the British Empi...",94.0,Christopher Nolan,Fionn Whitehead,Barry Keoghan,Mark Rylance,Tom Hardy,555092,188373161.0,1.777105e+06
722,Deadpool 2,2018.0,R,119,"Action, Adventure, Comedy",7.7,Foul-mouthed mutant mercenary Wade Wilson (a.k...,66.0,David Leitch,Ryan Reynolds,Josh Brolin,Morena Baccarin,Julian Dennison,478586,324591735.0,2.727662e+06
725,Mission: Impossible - Fallout,2018.0,UA,147,"Action, Adventure, Thriller",7.7,"Ethan Hunt and his IMF team, along with some f...",86.0,Christopher McQuarrie,Tom Cruise,Henry Cavill,Ving Rhames,Simon Pegg,291257,220159104.0,1.497681e+06
887,Guardians of the Galaxy Vol. 2,2017.0,UA,136,"Action, Adventure, Comedy",7.6,The Guardians struggle to keep together as a t...,67.0,James Gunn,Chris Pratt,Zoe Saldana,Dave Bautista,Vin Diesel,569974,389813101.0,2.866273e+06
888,Baby Driver,2017.0,UA,113,"Action, Crime, Drama",7.6,After being coerced into working for a crime b...,86.0,Edgar Wright,Ansel Elgort,Jon Bernthal,Jon Hamm,Eiza González,439406,107825862.0,9.542112e+05
889,Only the Brave,2017.0,UA,134,"Action, Biography, Drama",7.6,Based on the true story of the Granite Mountai...,72.0,Joseph Kosinski,Josh Brolin,Miles Teller,Jeff Bridges,Jennifer Connelly,58371,18340051.0,1.368661e+05
891,Incredibles 2,2018.0,UA,118,"Animation, Action, Adventure",7.6,The Incredibles family takes on a new mission ...,80.0,Brad Bird,Craig T. Nelson,Holly Hunter,Sarah Vowell,Huck Milner,250057,608581744.0,5.157472e+06